// ==============================================================
// Generated by Vitis HLS v2023.1.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mm2s_mm2s,hls_ip_2023_1_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvc1902-vsvd1760-2MP-e-S,HLS_INPUT_CLOCK=3.333000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.433090,HLS_SYN_LAT=268435534,HLS_SYN_TPT=none,HLS_SYN_MEM=16,HLS_SYN_DSP=0,HLS_SYN_FF=2968,HLS_SYN_LUT=3252,HLS_VERSION=2023_1_2}" *)

module mm2s (
        ap_clk,
        ap_rst_n,
        event_done,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        outA_TDATA,
        outA_TVALID,
        outA_TREADY,
        outB_TDATA,
        outB_TVALID,
        outB_TREADY,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt,
        event_start,
        stall_start_ext,
        stall_done_ext,
        stall_start_str,
        stall_done_str,
        stall_start_int,
        stall_done_int
);

parameter    ap_ST_fsm_state1 = 77'd1;
parameter    ap_ST_fsm_state2 = 77'd2;
parameter    ap_ST_fsm_state3 = 77'd4;
parameter    ap_ST_fsm_state4 = 77'd8;
parameter    ap_ST_fsm_state5 = 77'd16;
parameter    ap_ST_fsm_state6 = 77'd32;
parameter    ap_ST_fsm_state7 = 77'd64;
parameter    ap_ST_fsm_state8 = 77'd128;
parameter    ap_ST_fsm_state9 = 77'd256;
parameter    ap_ST_fsm_state10 = 77'd512;
parameter    ap_ST_fsm_state11 = 77'd1024;
parameter    ap_ST_fsm_state12 = 77'd2048;
parameter    ap_ST_fsm_state13 = 77'd4096;
parameter    ap_ST_fsm_state14 = 77'd8192;
parameter    ap_ST_fsm_state15 = 77'd16384;
parameter    ap_ST_fsm_state16 = 77'd32768;
parameter    ap_ST_fsm_state17 = 77'd65536;
parameter    ap_ST_fsm_state18 = 77'd131072;
parameter    ap_ST_fsm_state19 = 77'd262144;
parameter    ap_ST_fsm_state20 = 77'd524288;
parameter    ap_ST_fsm_state21 = 77'd1048576;
parameter    ap_ST_fsm_state22 = 77'd2097152;
parameter    ap_ST_fsm_state23 = 77'd4194304;
parameter    ap_ST_fsm_state24 = 77'd8388608;
parameter    ap_ST_fsm_state25 = 77'd16777216;
parameter    ap_ST_fsm_state26 = 77'd33554432;
parameter    ap_ST_fsm_state27 = 77'd67108864;
parameter    ap_ST_fsm_state28 = 77'd134217728;
parameter    ap_ST_fsm_state29 = 77'd268435456;
parameter    ap_ST_fsm_state30 = 77'd536870912;
parameter    ap_ST_fsm_state31 = 77'd1073741824;
parameter    ap_ST_fsm_state32 = 77'd2147483648;
parameter    ap_ST_fsm_state33 = 77'd4294967296;
parameter    ap_ST_fsm_state34 = 77'd8589934592;
parameter    ap_ST_fsm_state35 = 77'd17179869184;
parameter    ap_ST_fsm_state36 = 77'd34359738368;
parameter    ap_ST_fsm_state37 = 77'd68719476736;
parameter    ap_ST_fsm_state38 = 77'd137438953472;
parameter    ap_ST_fsm_state39 = 77'd274877906944;
parameter    ap_ST_fsm_state40 = 77'd549755813888;
parameter    ap_ST_fsm_state41 = 77'd1099511627776;
parameter    ap_ST_fsm_state42 = 77'd2199023255552;
parameter    ap_ST_fsm_state43 = 77'd4398046511104;
parameter    ap_ST_fsm_state44 = 77'd8796093022208;
parameter    ap_ST_fsm_state45 = 77'd17592186044416;
parameter    ap_ST_fsm_state46 = 77'd35184372088832;
parameter    ap_ST_fsm_state47 = 77'd70368744177664;
parameter    ap_ST_fsm_state48 = 77'd140737488355328;
parameter    ap_ST_fsm_state49 = 77'd281474976710656;
parameter    ap_ST_fsm_state50 = 77'd562949953421312;
parameter    ap_ST_fsm_state51 = 77'd1125899906842624;
parameter    ap_ST_fsm_state52 = 77'd2251799813685248;
parameter    ap_ST_fsm_state53 = 77'd4503599627370496;
parameter    ap_ST_fsm_state54 = 77'd9007199254740992;
parameter    ap_ST_fsm_state55 = 77'd18014398509481984;
parameter    ap_ST_fsm_state56 = 77'd36028797018963968;
parameter    ap_ST_fsm_state57 = 77'd72057594037927936;
parameter    ap_ST_fsm_state58 = 77'd144115188075855872;
parameter    ap_ST_fsm_state59 = 77'd288230376151711744;
parameter    ap_ST_fsm_state60 = 77'd576460752303423488;
parameter    ap_ST_fsm_state61 = 77'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 77'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 77'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 77'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 77'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 77'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 77'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 77'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 77'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 77'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 77'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 77'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 77'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 77'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 77'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 77'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 77'd75557863725914323419136;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (128 / 8);

input   ap_clk;
input   ap_rst_n;
output   event_done;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;
output  [127:0] outA_TDATA;
output   outA_TVALID;
input   outA_TREADY;
output  [127:0] outB_TDATA;
output   outB_TVALID;
input   outB_TREADY;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;
output   event_start;
output   stall_start_ext;
output   stall_done_ext;
output   stall_start_str;
output   stall_done_str;
output   stall_start_int;
output   stall_done_int;

reg stall_start_ext;
reg stall_done_ext;
reg stall_start_str;
reg stall_done_str;
reg stall_start_int;
reg stall_done_int;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [76:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] size;
wire   [63:0] inputA;
wire   [63:0] inputB;
reg    gmem1_blk_n_AR;
wire    ap_CS_fsm_state4;
reg    gmem2_blk_n_AR;
reg   [0:0] tmp_reg_253;
reg    ap_block_state1;
reg   [29:0] p_lshr_cast_reg_258;
reg   [29:0] p_lshr_f_cast_reg_263;
wire   [30:0] div_fu_185_p3;
reg   [30:0] div_reg_268;
wire    ap_CS_fsm_state2;
wire   [29:0] trunc_ln47_fu_192_p1;
reg   [29:0] trunc_ln47_reg_274;
reg   [59:0] trunc_ln_reg_279;
wire    ap_CS_fsm_state3;
wire   [29:0] empty_fu_211_p3;
reg   [29:0] empty_reg_285;
reg   [59:0] trunc_ln47_1_reg_290;
wire    gmem1_AWREADY;
wire    gmem1_WREADY;
reg    gmem1_ARVALID;
wire    gmem1_ARREADY;
reg   [63:0] gmem1_ARADDR;
reg   [31:0] gmem1_ARLEN;
wire    gmem1_RVALID;
reg    gmem1_RREADY;
wire   [127:0] gmem1_RDATA;
wire   [8:0] gmem1_RFIFONUM;
wire    gmem1_BVALID;
wire    gmem2_AWREADY;
wire    gmem2_WREADY;
reg    gmem2_ARVALID;
wire    gmem2_ARREADY;
reg   [63:0] gmem2_ARADDR;
reg   [31:0] gmem2_ARLEN;
wire    gmem2_RVALID;
reg    gmem2_RREADY;
wire   [127:0] gmem2_RDATA;
wire   [8:0] gmem2_RFIFONUM;
wire    gmem2_BVALID;
reg    ap_block_state4_io;
wire   [31:0] zext_ln47_fu_238_p1;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_start;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_done;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_idle;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_ready;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWVALID;
wire   [63:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWADDR;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWID;
wire   [31:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWLEN;
wire   [2:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWSIZE;
wire   [1:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWBURST;
wire   [1:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWLOCK;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWCACHE;
wire   [2:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWPROT;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWQOS;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWREGION;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWUSER;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_WVALID;
wire   [127:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_WDATA;
wire   [15:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_WSTRB;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_WLAST;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_WID;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_WUSER;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARVALID;
wire   [63:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARADDR;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARID;
wire   [31:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARLEN;
wire   [2:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARSIZE;
wire   [1:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARBURST;
wire   [1:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARLOCK;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARCACHE;
wire   [2:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARPROT;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARQOS;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARREGION;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARUSER;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_RREADY;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_BREADY;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWVALID;
wire   [63:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWADDR;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWID;
wire   [31:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWLEN;
wire   [2:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWSIZE;
wire   [1:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWBURST;
wire   [1:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWLOCK;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWCACHE;
wire   [2:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWPROT;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWQOS;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWREGION;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWUSER;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_WVALID;
wire   [127:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_WDATA;
wire   [15:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_WSTRB;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_WLAST;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_WID;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_WUSER;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARVALID;
wire   [63:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARADDR;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARID;
wire   [31:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARLEN;
wire   [2:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARSIZE;
wire   [1:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARBURST;
wire   [1:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARLOCK;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARCACHE;
wire   [2:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARPROT;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARQOS;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARREGION;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARUSER;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_RREADY;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_BREADY;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outA_TREADY;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outB_TREADY;
wire   [127:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outA_TDATA;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outA_TVALID;
wire   [127:0] grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outB_TDATA;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outB_TVALID;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_ext_blocking_n;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_str_blocking_n;
wire    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_int_blocking_n;
reg    grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_start_reg;
wire    ap_CS_fsm_state75;
wire    ap_CS_fsm_state76;
wire  signed [63:0] sext_ln47_fu_228_p1;
wire  signed [63:0] sext_ln47_1_fu_243_p1;
wire   [31:0] p_neg_fu_147_p2;
wire   [30:0] p_lshr_cast_cast_fu_173_p1;
wire   [30:0] p_neg_t_fu_176_p2;
wire   [30:0] p_lshr_f_cast_cast_fu_182_p1;
wire   [0:0] icmp_ln47_fu_196_p2;
wire    ap_CS_fsm_state77;
wire    regslice_both_outA_U_apdone_blk;
wire    regslice_both_outB_U_apdone_blk;
reg    ap_block_state77;
reg   [76:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
reg    ap_ST_fsm_state76_blk;
reg    ap_ST_fsm_state77_blk;
wire    ap_ext_blocking_cur_n;
reg    ap_ext_blocking_sub_n;
reg    ap_wait_0;
reg    ap_sub_ext_blocking_0;
reg    ap_str_blocking_sub_n;
reg    ap_sub_str_blocking_0;
reg    ap_int_blocking_sub_n;
reg    ap_sub_int_blocking_0;
wire    ap_ext_blocking_n;
wire    ap_str_blocking_n;
wire    ap_int_blocking_n;
reg    ap_ext_blocking_n_reg;
reg    ap_str_blocking_n_reg;
reg    ap_int_blocking_n_reg;
wire    outA_TREADY_int_regslice;
wire    regslice_both_outA_U_vld_out;
wire    outB_TREADY_int_regslice;
wire    regslice_both_outB_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 77'd1;
#0 grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_start_reg = 1'b0;
end

mm2s_mm2s_Pipeline_VITIS_LOOP_47_1 grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_start),
    .ap_done(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_done),
    .ap_idle(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_idle),
    .ap_ready(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_ready),
    .m_axi_gmem1_AWVALID(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(gmem1_RVALID),
    .m_axi_gmem1_RREADY(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(gmem1_RDATA),
    .m_axi_gmem1_RLAST(1'b0),
    .m_axi_gmem1_RID(1'd0),
    .m_axi_gmem1_RFIFONUM(gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(1'd0),
    .m_axi_gmem1_RRESP(2'd0),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .m_axi_gmem2_AWVALID(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWVALID),
    .m_axi_gmem2_AWREADY(1'b0),
    .m_axi_gmem2_AWADDR(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWADDR),
    .m_axi_gmem2_AWID(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWID),
    .m_axi_gmem2_AWLEN(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWLEN),
    .m_axi_gmem2_AWSIZE(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWSIZE),
    .m_axi_gmem2_AWBURST(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWBURST),
    .m_axi_gmem2_AWLOCK(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWLOCK),
    .m_axi_gmem2_AWCACHE(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWCACHE),
    .m_axi_gmem2_AWPROT(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWPROT),
    .m_axi_gmem2_AWQOS(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWQOS),
    .m_axi_gmem2_AWREGION(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWREGION),
    .m_axi_gmem2_AWUSER(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_AWUSER),
    .m_axi_gmem2_WVALID(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_WVALID),
    .m_axi_gmem2_WREADY(1'b0),
    .m_axi_gmem2_WDATA(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_WDATA),
    .m_axi_gmem2_WSTRB(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_WSTRB),
    .m_axi_gmem2_WLAST(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_WLAST),
    .m_axi_gmem2_WID(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_WID),
    .m_axi_gmem2_WUSER(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_WUSER),
    .m_axi_gmem2_ARVALID(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARVALID),
    .m_axi_gmem2_ARREADY(gmem2_ARREADY),
    .m_axi_gmem2_ARADDR(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARADDR),
    .m_axi_gmem2_ARID(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARID),
    .m_axi_gmem2_ARLEN(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARLEN),
    .m_axi_gmem2_ARSIZE(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARSIZE),
    .m_axi_gmem2_ARBURST(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARBURST),
    .m_axi_gmem2_ARLOCK(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARLOCK),
    .m_axi_gmem2_ARCACHE(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARCACHE),
    .m_axi_gmem2_ARPROT(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARPROT),
    .m_axi_gmem2_ARQOS(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARQOS),
    .m_axi_gmem2_ARREGION(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARREGION),
    .m_axi_gmem2_ARUSER(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARUSER),
    .m_axi_gmem2_RVALID(gmem2_RVALID),
    .m_axi_gmem2_RREADY(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_RREADY),
    .m_axi_gmem2_RDATA(gmem2_RDATA),
    .m_axi_gmem2_RLAST(1'b0),
    .m_axi_gmem2_RID(1'd0),
    .m_axi_gmem2_RFIFONUM(gmem2_RFIFONUM),
    .m_axi_gmem2_RUSER(1'd0),
    .m_axi_gmem2_RRESP(2'd0),
    .m_axi_gmem2_BVALID(1'b0),
    .m_axi_gmem2_BREADY(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_BREADY),
    .m_axi_gmem2_BRESP(2'd0),
    .m_axi_gmem2_BID(1'd0),
    .m_axi_gmem2_BUSER(1'd0),
    .outA_TREADY(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outA_TREADY),
    .outB_TREADY(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outB_TREADY),
    .sext_ln47_1(trunc_ln47_1_reg_290),
    .sext_ln47(trunc_ln_reg_279),
    .div(div_reg_268),
    .outA_TDATA(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outA_TDATA),
    .outA_TVALID(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outA_TVALID),
    .outB_TDATA(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outB_TDATA),
    .outB_TVALID(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outB_TVALID),
    .ap_ext_blocking_n(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_str_blocking_n),
    .ap_int_blocking_n(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_int_blocking_n)
);

mm2s_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .size(size),
    .inputA(inputA),
    .inputB(inputB),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .event_start(event_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

mm2s_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 69 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 128 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem1_ARVALID),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(gmem1_ARADDR),
    .I_ARLEN(gmem1_ARLEN),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(gmem1_RREADY),
    .I_RDATA(gmem1_RDATA),
    .I_RFIFONUM(gmem1_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(128'd0),
    .I_WSTRB(16'd0),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(1'b0)
);

mm2s_gmem2_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 69 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 128 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem2_ARVALID),
    .I_ARREADY(gmem2_ARREADY),
    .I_ARADDR(gmem2_ARADDR),
    .I_ARLEN(gmem2_ARLEN),
    .I_RVALID(gmem2_RVALID),
    .I_RREADY(gmem2_RREADY),
    .I_RDATA(gmem2_RDATA),
    .I_RFIFONUM(gmem2_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem2_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem2_WREADY),
    .I_WDATA(128'd0),
    .I_WSTRB(16'd0),
    .I_BVALID(gmem2_BVALID),
    .I_BREADY(1'b0)
);

mm2s_regslice_both #(
    .DataWidth( 128 ))
regslice_both_outA_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outA_TDATA),
    .vld_in(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outA_TVALID),
    .ack_in(outA_TREADY_int_regslice),
    .data_out(outA_TDATA),
    .vld_out(regslice_both_outA_U_vld_out),
    .ack_out(outA_TREADY),
    .apdone_blk(regslice_both_outA_U_apdone_blk)
);

mm2s_regslice_both #(
    .DataWidth( 128 ))
regslice_both_outB_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outB_TDATA),
    .vld_in(grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outB_TVALID),
    .ack_in(outB_TREADY_int_regslice),
    .data_out(outB_TDATA),
    .vld_out(regslice_both_outB_U_vld_out),
    .ack_out(outB_TREADY),
    .apdone_blk(regslice_both_outB_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((regslice_both_outB_U_apdone_blk == 1'b1) | (regslice_both_outA_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state77))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state75)) begin
            grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_start_reg <= 1'b1;
        end else if ((grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_ready == 1'b1)) begin
            grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_ext_blocking_n_reg <= ap_ext_blocking_n;
end

always @ (posedge ap_clk) begin
    ap_int_blocking_n_reg <= ap_int_blocking_n;
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    ap_str_blocking_n_reg <= ap_str_blocking_n;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        div_reg_268 <= div_fu_185_p3;
        trunc_ln47_reg_274 <= trunc_ln47_fu_192_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        empty_reg_285 <= empty_fu_211_p3;
        trunc_ln47_1_reg_290 <= {{inputB[63:4]}};
        trunc_ln_reg_279 <= {{inputA[63:4]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_lshr_cast_reg_258 <= {{p_neg_fu_147_p2[31:2]}};
        p_lshr_f_cast_reg_263 <= {{size[31:2]}};
        tmp_reg_253 <= size[32'd31];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_io)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

always @ (*) begin
    if ((grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_done == 1'b0)) begin
        ap_ST_fsm_state76_blk = 1'b1;
    end else begin
        ap_ST_fsm_state76_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_outB_U_apdone_blk == 1'b1) | (regslice_both_outA_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state77_blk = 1'b1;
    end else begin
        ap_ST_fsm_state77_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((~((regslice_both_outB_U_apdone_blk == 1'b1) | (regslice_both_outA_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state77))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_wait_0 & ap_sub_ext_blocking_0) == 1'b1)) begin
        ap_ext_blocking_sub_n = 1'b0;
    end else begin
        ap_ext_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_wait_0 & ap_sub_int_blocking_0) == 1'b1)) begin
        ap_int_blocking_sub_n = 1'b0;
    end else begin
        ap_int_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((regslice_both_outB_U_apdone_blk == 1'b1) | (regslice_both_outA_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state77))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_wait_0 & ap_sub_str_blocking_0) == 1'b1)) begin
        ap_str_blocking_sub_n = 1'b0;
    end else begin
        ap_str_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if ((grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_0 = 1'b1;
    end else begin
        ap_sub_ext_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_0 = 1'b1;
    end else begin
        ap_sub_int_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_0 = 1'b1;
    end else begin
        ap_sub_str_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_state76 == ap_CS_fsm)) begin
        ap_wait_0 = 1'b1;
    end else begin
        ap_wait_0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_io) & (1'b1 == ap_CS_fsm_state4))) begin
        gmem1_ARADDR = sext_ln47_fu_228_p1;
    end else if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        gmem1_ARADDR = grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARADDR;
    end else begin
        gmem1_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_io) & (1'b1 == ap_CS_fsm_state4))) begin
        gmem1_ARLEN = zext_ln47_fu_238_p1;
    end else if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        gmem1_ARLEN = grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARLEN;
    end else begin
        gmem1_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_io) & (1'b1 == ap_CS_fsm_state4))) begin
        gmem1_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        gmem1_ARVALID = grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_ARVALID;
    end else begin
        gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        gmem1_RREADY = grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem1_RREADY;
    end else begin
        gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_io) & (1'b1 == ap_CS_fsm_state4))) begin
        gmem2_ARADDR = sext_ln47_1_fu_243_p1;
    end else if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        gmem2_ARADDR = grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARADDR;
    end else begin
        gmem2_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_io) & (1'b1 == ap_CS_fsm_state4))) begin
        gmem2_ARLEN = zext_ln47_fu_238_p1;
    end else if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        gmem2_ARLEN = grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARLEN;
    end else begin
        gmem2_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_io) & (1'b1 == ap_CS_fsm_state4))) begin
        gmem2_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        gmem2_ARVALID = grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_ARVALID;
    end else begin
        gmem2_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        gmem2_RREADY = grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_m_axi_gmem2_RREADY;
    end else begin
        gmem2_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gmem2_blk_n_AR = m_axi_gmem2_ARREADY;
    end else begin
        gmem2_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_ext_blocking_n_reg == 1'b0) & (ap_ext_blocking_n == 1'b1))) begin
        stall_done_ext = 1'b1;
    end else begin
        stall_done_ext = 1'b0;
    end
end

always @ (*) begin
    if (((ap_int_blocking_n_reg == 1'b0) & (ap_int_blocking_n == 1'b1))) begin
        stall_done_int = 1'b1;
    end else begin
        stall_done_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_str_blocking_n_reg == 1'b0) & (ap_str_blocking_n == 1'b1))) begin
        stall_done_str = 1'b1;
    end else begin
        stall_done_str = 1'b0;
    end
end

always @ (*) begin
    if (((ap_ext_blocking_n_reg == 1'b1) & (ap_ext_blocking_n == 1'b0))) begin
        stall_start_ext = 1'b1;
    end else begin
        stall_start_ext = 1'b0;
    end
end

always @ (*) begin
    if (((ap_int_blocking_n_reg == 1'b1) & (ap_int_blocking_n == 1'b0))) begin
        stall_start_int = 1'b1;
    end else begin
        stall_start_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_str_blocking_n_reg == 1'b1) & (ap_str_blocking_n == 1'b0))) begin
        stall_start_str = 1'b1;
    end else begin
        stall_start_str = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_io) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            if (((grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state76))) begin
                ap_NS_fsm = ap_ST_fsm_state77;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state76;
            end
        end
        ap_ST_fsm_state77 : begin
            if ((~((regslice_both_outB_U_apdone_blk == 1'b1) | (regslice_both_outA_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state77))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state77;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state4_io = ((gmem2_ARREADY == 1'b0) | (gmem1_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_state77 = ((regslice_both_outB_U_apdone_blk == 1'b1) | (regslice_both_outA_U_apdone_blk == 1'b1));
end

assign ap_ext_blocking_cur_n = (gmem2_blk_n_AR & gmem1_blk_n_AR);

assign ap_ext_blocking_n = (ap_ext_blocking_sub_n & ap_ext_blocking_cur_n);

assign ap_int_blocking_n = (ap_int_blocking_sub_n & 1'b1);

assign ap_str_blocking_n = (ap_str_blocking_sub_n & 1'b1);

assign div_fu_185_p3 = ((tmp_reg_253[0:0] == 1'b1) ? p_neg_t_fu_176_p2 : p_lshr_f_cast_cast_fu_182_p1);

assign empty_fu_211_p3 = ((icmp_ln47_fu_196_p2[0:0] == 1'b1) ? trunc_ln47_reg_274 : 30'd0);

assign event_done = ap_done;

assign grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_start = grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_ap_start_reg;

assign grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outA_TREADY = (outA_TREADY_int_regslice & ap_CS_fsm_state76);

assign grp_mm2s_Pipeline_VITIS_LOOP_47_1_fu_124_outB_TREADY = (outB_TREADY_int_regslice & ap_CS_fsm_state76);

assign icmp_ln47_fu_196_p2 = (($signed(div_reg_268) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign outA_TVALID = regslice_both_outA_U_vld_out;

assign outB_TVALID = regslice_both_outB_U_vld_out;

assign p_lshr_cast_cast_fu_173_p1 = p_lshr_cast_reg_258;

assign p_lshr_f_cast_cast_fu_182_p1 = p_lshr_f_cast_reg_263;

assign p_neg_fu_147_p2 = (32'd0 - size);

assign p_neg_t_fu_176_p2 = (31'd0 - p_lshr_cast_cast_fu_173_p1);

assign sext_ln47_1_fu_243_p1 = $signed(trunc_ln47_1_reg_290);

assign sext_ln47_fu_228_p1 = $signed(trunc_ln_reg_279);

assign trunc_ln47_fu_192_p1 = div_fu_185_p3[29:0];

assign zext_ln47_fu_238_p1 = empty_reg_285;


reg find_kernel_block = 0;
// synthesis translate_off
`include "mm2s_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //mm2s

