catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 

open_project mm2s
set_top mm2s
# v++ -g, -D, -I, --advanced.prop kernel.mm2s.kernel_flags
add_files "/home/gsorrentino/projects/voted_hdl/voted/fpga/mm2s.cpp" -cflags " -g"
open_solution -flow_target vitis solution
set_part xcvc1902-vsvd1760-2MP-e-S
create_clock -period 299.996999MHz -name default
# v++ -g or --profile_kernel stall
config_rtl -kernel_profile
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ -g
config_debug -enable
# v++ --advanced.param compiler.deadlockDetection
config_rtl -deadlock_detection sim
# v++ --advanced.param compiler.axiDeadLockFree
config_interface -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format xo -ipname mm2s
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
